export interface MockProduct {
  id: string
  title: string
  price: string
  priceValue: number
  originalPrice?: string
  imageUrl: string
  material: string
  badge?: string
  badgeVariant?: 'orange' | 'brown' | 'gold'
  href: string
  inStock: boolean
  /** Lowercase Medusa tags. Used by filter chips; falls back to `material` when absent. */
  tags?: string[]
}

export interface MockCollection {
  handle: string
  title: string
  subtitle: string
  heroImageUrl: string
  products: MockProduct[]
}

const collections: MockCollection[] = [
  {
    handle: 'living-room',
    title: 'Living Room',
    subtitle: 'Where comfort meets artisanship',
    heroImageUrl: '',
    products: [
      {
        id: 'lr-001',
        title: 'Ōkura Lounge Chair',
        price: '₹38,500',
        priceValue: 38500,
        imageUrl: '',
        material: 'Linen',
        badge: 'BESTSELLER',
        badgeVariant: 'orange',
        href: '/products/okura-lounge-chair',
        inStock: true,
      },
      {
        id: 'lr-002',
        title: 'Aranya Teak Coffee Table',
        price: '₹24,900',
        priceValue: 24900,
        originalPrice: '₹28,000',
        imageUrl: '',
        material: 'Wood',
        href: '/products/aranya-teak-coffee-table',
        inStock: true,
      },
      {
        id: 'lr-003',
        title: 'Sahara Floor Lamp',
        price: '₹12,500',
        priceValue: 12500,
        imageUrl: '',
        material: 'Brass',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/sahara-floor-lamp',
        inStock: true,
      },
      {
        id: 'lr-004',
        title: 'Ivory Jute Area Rug',
        price: '₹9,800',
        priceValue: 9800,
        imageUrl: '',
        material: 'Rattan',
        href: '/products/ivory-jute-area-rug',
        inStock: true,
      },
      {
        id: 'lr-005',
        title: 'Malabar Side Table',
        price: '₹14,200',
        priceValue: 14200,
        imageUrl: '',
        material: 'Marble',
        href: '/products/malabar-side-table',
        inStock: false,
      },
      {
        id: 'lr-006',
        title: 'Kantha Throw Cushion Set',
        price: '₹3,600',
        priceValue: 3600,
        imageUrl: '',
        material: 'Linen',
        href: '/products/kantha-throw-cushion',
        inStock: true,
      },
      {
        id: 'lr-007',
        title: 'Dune Ceramic Vase',
        price: '₹5,400',
        priceValue: 5400,
        imageUrl: '',
        material: 'Ceramic',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/dune-ceramic-vase',
        inStock: true,
      },
      {
        id: 'lr-008',
        title: 'Rattan Pendant Light',
        price: '₹8,200',
        priceValue: 8200,
        imageUrl: '',
        material: 'Rattan',
        href: '/products/rattan-pendant-light',
        inStock: true,
      },
    ],
  },
  {
    handle: 'dining',
    title: 'Dining',
    subtitle: 'Set the perfect table',
    heroImageUrl: '',
    products: [
      {
        id: 'dn-001',
        title: 'Haveli Dining Table',
        price: '₹68,000',
        priceValue: 68000,
        imageUrl: '',
        material: 'Wood',
        badge: 'BESTSELLER',
        badgeVariant: 'orange',
        href: '/products/haveli-dining-table',
        inStock: true,
      },
      {
        id: 'dn-002',
        title: 'Woven Rattan Dining Chair',
        price: '₹11,500',
        priceValue: 11500,
        imageUrl: '',
        material: 'Rattan',
        href: '/products/woven-rattan-dining-chair',
        inStock: true,
      },
      {
        id: 'dn-003',
        title: 'Brass Candle Holder Set',
        price: '₹4,800',
        priceValue: 4800,
        imageUrl: '',
        material: 'Brass',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/brass-candle-holder',
        inStock: true,
      },
      {
        id: 'dn-004',
        title: 'Indigo Linen Table Runner',
        price: '₹2,200',
        priceValue: 2200,
        originalPrice: '₹2,800',
        imageUrl: '',
        material: 'Linen',
        href: '/products/indigo-linen-table-runner',
        inStock: true,
      },
      {
        id: 'dn-005',
        title: 'Marble Serving Board',
        price: '₹7,600',
        priceValue: 7600,
        imageUrl: '',
        material: 'Marble',
        href: '/products/marble-serving-board',
        inStock: true,
      },
      {
        id: 'dn-006',
        title: 'Terracotta Dinner Set',
        price: '₹16,400',
        priceValue: 16400,
        imageUrl: '',
        material: 'Ceramic',
        href: '/products/terracotta-dinner-set',
        inStock: false,
      },
    ],
  },
  {
    handle: 'bedroom',
    title: 'Bedroom',
    subtitle: 'Your sanctuary of rest',
    heroImageUrl: '',
    products: [
      {
        id: 'br-001',
        title: 'Jaisalmer Carved Bed Frame',
        price: '₹84,000',
        priceValue: 84000,
        imageUrl: '',
        material: 'Wood',
        badge: 'BESTSELLER',
        badgeVariant: 'orange',
        href: '/products/jaisalmer-carved-bed',
        inStock: true,
      },
      {
        id: 'br-002',
        title: 'Ivory Linen Bedding Set',
        price: '₹12,800',
        priceValue: 12800,
        imageUrl: '',
        material: 'Linen',
        href: '/products/ivory-linen-bedding',
        inStock: true,
      },
      {
        id: 'br-003',
        title: 'Mango Wood Nightstand',
        price: '₹18,500',
        priceValue: 18500,
        imageUrl: '',
        material: 'Wood',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/mango-wood-nightstand',
        inStock: true,
      },
      {
        id: 'br-004',
        title: 'Brass Bedside Lamp',
        price: '₹9,200',
        priceValue: 9200,
        imageUrl: '',
        material: 'Brass',
        href: '/products/brass-bedside-lamp',
        inStock: true,
      },
      {
        id: 'br-005',
        title: 'Rattan Wardrobe',
        price: '₹42,000',
        priceValue: 42000,
        originalPrice: '₹48,000',
        imageUrl: '',
        material: 'Rattan',
        href: '/products/rattan-wardrobe',
        inStock: true,
      },
      {
        id: 'br-006',
        title: 'Ornate Vanity Mirror',
        price: '₹22,000',
        priceValue: 22000,
        imageUrl: '',
        material: 'Glass',
        href: '/products/ornate-vanity-mirror',
        inStock: false,
      },
    ],
  },
  {
    handle: 'home-office',
    title: 'Home Office',
    subtitle: 'Work beautifully',
    heroImageUrl: '',
    products: [
      {
        id: 'ho-001',
        title: 'Sheesham Executive Desk',
        price: '₹54,000',
        priceValue: 54000,
        imageUrl: '',
        material: 'Wood',
        badge: 'BESTSELLER',
        badgeVariant: 'orange',
        href: '/products/sheesham-executive-desk',
        inStock: true,
      },
      {
        id: 'ho-002',
        title: 'Brass Desk Organiser',
        price: '₹6,800',
        priceValue: 6800,
        imageUrl: '',
        material: 'Brass',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/brass-desk-organiser',
        inStock: true,
      },
      {
        id: 'ho-003',
        title: 'Rattan Bookshelf',
        price: '₹31,000',
        priceValue: 31000,
        imageUrl: '',
        material: 'Rattan',
        href: '/products/rattan-bookshelf',
        inStock: true,
      },
      {
        id: 'ho-004',
        title: 'Marble Desk Tray',
        price: '₹4,500',
        priceValue: 4500,
        imageUrl: '',
        material: 'Marble',
        href: '/products/marble-desk-tray',
        inStock: true,
      },
      {
        id: 'ho-005',
        title: 'Ergonomic Linen Task Chair',
        price: '₹28,500',
        priceValue: 28500,
        originalPrice: '₹33,000',
        imageUrl: '',
        material: 'Linen',
        href: '/products/linen-task-chair',
        inStock: true,
      },
    ],
  },
  {
    handle: 'outdoor',
    title: 'Outdoor',
    subtitle: 'Bring luxury outdoors',
    heroImageUrl: '',
    products: [
      {
        id: 'ot-001',
        title: 'Teak Garden Chair',
        price: '₹22,500',
        priceValue: 22500,
        imageUrl: '',
        material: 'Wood',
        badge: 'BESTSELLER',
        badgeVariant: 'orange',
        href: '/products/teak-garden-chair',
        inStock: true,
      },
      {
        id: 'ot-002',
        title: 'Hand-Thrown Planter Set',
        price: '₹8,900',
        priceValue: 8900,
        imageUrl: '',
        material: 'Ceramic',
        badge: 'NEW',
        badgeVariant: 'gold',
        href: '/products/hand-thrown-planter',
        inStock: true,
      },
      {
        id: 'ot-003',
        title: 'Rattan Garden Loveseat',
        price: '₹45,000',
        priceValue: 45000,
        originalPrice: '₹52,000',
        imageUrl: '',
        material: 'Rattan',
        href: '/products/rattan-garden-loveseat',
        inStock: true,
      },
      {
        id: 'ot-004',
        title: 'Brass Outdoor Lantern',
        price: '₹7,200',
        priceValue: 7200,
        imageUrl: '',
        material: 'Brass',
        href: '/products/brass-outdoor-lantern',
        inStock: true,
      },
      {
        id: 'ot-005',
        title: 'Stone Garden Table',
        price: '₹36,800',
        priceValue: 36800,
        imageUrl: '',
        material: 'Marble',
        href: '/products/stone-garden-table',
        inStock: false,
      },
    ],
  },
]

export function getCollectionMock(handle: string): MockCollection | null {
  return collections.find((c) => c.handle === handle) ?? null
}

export function getAllCollectionHandles(): string[] {
  return collections.map((c) => c.handle)
}

export { collections as allCollections }
